image:
  file: .gitpod.Dockerfile

tasks:
  - name: initial
    init: go install github.com/go-task/task/v3/cmd/task@latest &&
      go install honnef.co/go/tools/cmd/staticcheck@latest &&
      go install golang.org/x/tools/cmd/goimports@latest &&
      task build
    command: go version

vscode:
  extensions:
    - golang.go
